// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUXM1PN96chQUdbo8XU5BBHw1ms3IRl3s',
    appId: '1:706360373186:web:08529574a41272be75305b',
    messagingSenderId: '706360373186',
    projectId: 'tses-52494',
    authDomain: 'tses-52494.firebaseapp.com',
    storageBucket: 'tses-52494.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9wsEeFeERHgo4ZKwGk4dhtmbx3Q6T6w8',
    appId: '1:706360373186:android:848cd8d154cf998d75305b',
    messagingSenderId: '706360373186',
    projectId: 'tses-52494',
    storageBucket: 'tses-52494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDvSfgeiW2ssfWVL1EazxXKtIzX_OaRg',
    appId: '1:706360373186:ios:9eb2da49bcb9219075305b',
    messagingSenderId: '706360373186',
    projectId: 'tses-52494',
    storageBucket: 'tses-52494.appspot.com',
    iosBundleId: 'com.example.tsesapp.tsesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdDvSfgeiW2ssfWVL1EazxXKtIzX_OaRg',
    appId: '1:706360373186:ios:f102a5872b57a3a075305b',
    messagingSenderId: '706360373186',
    projectId: 'tses-52494',
    storageBucket: 'tses-52494.appspot.com',
    iosBundleId: 'com.example.tsesapp.tsesApp.RunnerTests',
  );
}
